### ISSUE TITLE
"TypeError: $ is not a function" with Image Annotation and when asked to reload the page

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6652]
Regressed with #5049.
