### ISSUE TITLE
Possible issue with Tomcat 8/Java 8

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2196]
The error is:

```
org.apache.catalina.core.StandardContext.filterStart Exception starting filter orbeon-xforms-filter
 java.lang.NoSuchMethodError: org.orbeon.private.scala.collection.immutable.StringOps.r()Lorg/orbeon/private/scala/util/matching/Regex;
	at org.orbeon.private.orbeon.oxf.servlet.FilterSettings$$anonfun$3.apply(OrbeonXFormsFilter.scala:28)
```

[+1 from evaluator](https://mail.google.com/mail/u/0/#search/%22Exception+starting+filter+orbeon-xforms-filter%22/14cc4c280d8d6885)
[+1 from customer](https://basecamp.com/1721271/projects/6131438/messages/41238642)

**Comment by ebruchez** [comment]
On OS X, I cannot reproduce  this so far with Java 1.8.0_25 and apache-tomcat-8.0.21 with build of 4.8.2 and 4.9.

Could it be just with the filter? The JSP examples do work though.

**Comment by ebruchez** [comment]
Still haven't reproduced the issue. But I tried to upgrade Proguard to the latest version, 5.2.1. However, that version crashes upon building, see:

- http://sourceforge.net/p/proguard/bugs/552/
- http://sourceforge.net/p/proguard/bugs/549/
- https://issues.scala-lang.org/browse/SI-8931
- https://github.com/scala/scala/pull/4080

So it seems we need to upgrade to Scala 2.11.5 (now 2.11.6) to upgrade Proguard (#1703).

This said, it's not clear whether an upgrade of Proguard would address the problem, but it might.

**Comment by ebruchez** [comment]
Report of another issue, after commenting out the filter, on Windows Server 2012 R2 64 Bit, Java 8 Update 45, Tomcat 8, with port 80/443 (might not be relevant). But works on same machine with Tomcat 7.0.61.

**Comment by ebruchez** [comment]
Scala 2.11.x upgrade and Proguard 5.2.x upgrade now done.

**Comment by ebruchez** [comment]
Maybe ask customer if can try build to see if issue persists after Scala/Proguard upgrades?

**Comment by ebruchez** [comment]
Next step: ship with 4.10 and ask customer to try 4.10 build if possible to see if Scala/Proguard upgrades fixed the issue.

**Comment by ebruchez** [comment]
Closing this for now as I have asked customer for feedback. Will reopen if feedback is negative.
